// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_go

type Application struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CvURL     string `json:"cvURL"`
	Job       Job    `json:"job"`
	CreatedAt string `json:"createdAt"`
}

type Job struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Location    string  `json:"location"`
	CreatedBy   User    `json:"createdBy"`
	CreatedAt   string  `json:"createdAt"`
	DeletedAt   *string `json:"deletedAt"`
}

type NewApplication struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	JobID string `json:"jobID"`
	CvURL string `json:"cvURL"`
}

type NewJob struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Location    string `json:"location"`
	CreatedByID string `json:"createdByID"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
